/* Copyright 2020 - 2026, Hansson Software. All rights reserved. */

#include "Commands.h"
#include "CommandRegistry.h"

#include <Commandlet.h>


#include <Platform/Winapi.h>
#include <Shlwapi.h>
#include <Shlobj.h>
#include <PathCch.h>
#include <Application/Application.h>

#pragma warning(disable : 6387)
#pragma warning(disable : 6031)

LOG_ADDCATEGORY(Commands);
LOG_ADDCATEGORY(Build);
LOG_ADDCATEGORY(Validator);
LOG_ADDCATEGORY(Persistent);

namespace Commands
{
	ADD_NEW_BUILD_COMMAND("-make", "Generates project files", Generate_Cmd);

	inline constexpr const char* InsertVcxprojFormatSpecifier()
	{
		constexpr const char* vcxprojTemplate =
			"<!-- Generated by MeteorBuild(R) -->\n"
			"<Project DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\n"
			" <ItemGroup Label=\"ProjectConfigurations\">\n"

			"  <ProjectConfiguration Include=\"Debug|x64\">\n"
			"   <Configuration>Debug</Configuration>\n"
			"   <Platform>x64</Platform>\n"
			"  </ProjectConfiguration>\n"
			"  <ProjectConfiguration Include=\"Development|x64\">\n"
			"   <Configuration>Development</Configuration>\n"
			"   <Platform>x64</Platform>\n"
			"  </ProjectConfiguration>\n"
			"  <ProjectConfiguration Include=\"Shipping|x64\">\n"
			"   <Configuration>Shipping</Configuration>\n"
			"   <Platform>x64</Platform>\n"
			"  </ProjectConfiguration>\n"
			" </ItemGroup>\n"

			" <PropertyGroup Label=\"Globals\">\n"
			"  <VCProjectVersion>18.0</VCProjectVersion>\n"
			"  <Keyword>Win32Proj</Keyword>\n"
			"  <ProjectGuid>%s</ProjectGuid>\n"
			" </PropertyGroup>\n"

			" <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.Default.props\"/>\n"

			" <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\" Label=\"Configuration\">\n"
			"  <ConfigurationType>Makefile</ConfigurationType>\n"
			"  <UseDebugLibraries>true</UseDebugLibraries>\n"
			"  <PlatformToolset>v145</PlatformToolset>\n"
			" </PropertyGroup>\n"
			" <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Development|x64'\" Label=\"Configuration\">\n"
			"  <ConfigurationType>Makefile</ConfigurationType>\n"
			"  <UseDebugLibraries>true</UseDebugLibraries>\n"
			"  <PlatformToolset>v145</PlatformToolset>\n"
			" </PropertyGroup>\n"
			" <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Shipping|x64'\" Label=\"Configuration\">\n"
			"  <ConfigurationType>Makefile</ConfigurationType>\n"
			"  <UseDebugLibraries>false</UseDebugLibraries>\n"
			"  <PlatformToolset>v145</PlatformToolset>\n"
			"  <WholeProgramOptimization>true</WholeProgramOptimization>\n"
			" </PropertyGroup>\n"
			" <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.props\" />\n"
			" <ImportGroup Label=\"ExtensionSettings\">\n"
			" </ImportGroup>\n"
			" <ImportGroup Label=\"Shared\">\n"
			" </ImportGroup>\n"

			" <ImportGroup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">\n"
			"  <Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\n"
			" </ImportGroup>\n"
			" <ImportGroup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Development|x64'\">\n"
			"  <Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\n"
			" </ImportGroup>\n"
			" <ImportGroup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Shipping|x64'\">\n"
			"  <Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\n"
			" </ImportGroup>\n"

			" <PropertyGroup Label=\"UserMacros\" />\n"
			" <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">\n"
			"  <NMakeBuildCommandLine>$(ProductDir)MeteorBuild.exe -build -c $(Configuration)</NMakeBuildCommandLine>\n"
			"  <NMakeReBuildCommandLine>$(ProductDir)MeteorBuild.exe -rebuild -c $(Configuration)</NMakeReBuildCommandLine>\n"
			"  <NMakeCleanCommandLine>$(ProductDir)MeteorBuild.exe -clean -c $(Configuration)</NMakeCleanCommandLine>\n"
			"  <NMakeOutput>%s.dll</NMakeOutput>\n"
			"  <NMakePreprocessorDefinitions>MR_DEBUG;$(NMakePreprocessorDefinitions)</NMakePreprocessorDefinitions>\n"
			"  <NMakeIncludeSearchPath>FILL HERE</NMakeIncludeSearchPath>\n"
			" </PropertyGroup>\n"
			" <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Development|x64'\">\n"
			"  <NMakeBuildCommandLine>$(ProductDir)MeteorBuild.exe -build -c $(Configuration)</NMakeBuildCommandLine>\n"
			"  <NMakeReBuildCommandLine>$(ProductDir)MeteorBuild.exe -rebuild -c $(Configuration)</NMakeReBuildCommandLine>\n"
			"  <NMakeCleanCommandLine>$(ProductDir)MeteorBuild.exe -clean -c $(Configuration)</NMakeCleanCommandLine>\n"
			"  <NMakeOutput>%s.dll</NMakeOutput>\n"
			"  <NMakePreprocessorDefinitions>MR_DEBUG;$(NMakePreprocessorDefinitions)</NMakePreprocessorDefinitions>\n"
			"  <NMakeIncludeSearchPath>FILL HERE</NMakeIncludeSearchPath>\n"
			" </PropertyGroup>\n"
			" <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Shipping|x64'\">\n"
			"  <NMakeBuildCommandLine>$(ProductDir)MeteorBuild.exe -build -c $(Configuration)</NMakeBuildCommandLine>\n"
			"  <NMakeReBuildCommandLine>$(ProductDir)MeteorBuild.exe -rebuild -c $(Configuration)</NMakeReBuildCommandLine>\n"
			"  <NMakeCleanCommandLine>$(ProductDir)MeteorBuild.exe -clean -c $(Configuration)</NMakeCleanCommandLine>\n"
			"  <NMakeOutput>%s.dll</NMakeOutput>\n"
			"  <NMakePreprocessorDefinitions>$(NMakePreprocessorDefinitions)</NMakePreprocessorDefinitions>\n"
			"  <NMakeIncludeSearchPath>FILL HERE</NMakeIncludeSearchPath>\n"
			" </PropertyGroup>\n"

			" <ItemGroup>\n"
			" </ItemGroup>\n"
			" <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.targets\" />\n"
			" <ImportGroup Label=\"ExtensionTargets\">\n"
			" </ImportGroup>\n"
			"</Project>";

		return vcxprojTemplate;
	}

	inline constexpr const char* InsertSlnxHeaderFormatSpecifier()
	{
		constexpr const char* slnxTemplate =
			"\n"
			"Microsoft Visual Studio Solution File, Format Version 12.00\n"
			"# Generated by MeteorBuild (R)\n"
			"# Visual Studio Version 18\n"
			"VisualStudioVersion = 18.6.11822.322 stable\n"
			"MinimumVisualStudioVersion = 10.0.40219.1"; // \n no need


		return slnxTemplate;
	}

	void Generate_Cmd()
	{
		LARGE_INTEGER startTime, endTime, frequency;
		QueryPerformanceCounter(&startTime);

		const String sourceDirectory = Commandlet::Get().Parse("-s");
		const String intermediateDirectory = Commandlet::Get().Parse("-i");

		// Arena allocates bytes, so equal size will be allocated!
		// WChar: 32 MB (Char / 2)
		// Char: 32 MB

#ifdef MR_PLATFORM_WINDOWS
		static MemoryBlockArena<wchar_t> arena = { 32_mB };
#else
		static MemoryBlockArena<char> arena = { 16_mB };
#endif // MR_PLATFORM_WINDOWS

		if (sourceDirectory && intermediateDirectory)
		{
			wchar_t* sourceDirectoryW = (wchar_t*)arena.Allocate(sourceDirectory.Length() * sizeof(wchar_t));
			if (!MultiByteToWideChar(CP_UTF8, 0, sourceDirectory, sourceDirectory.Length(), sourceDirectoryW, sourceDirectory.Length()))
			{
				MR_LOG(LogCommands, Error, "%s", *GetLastErrorString());
				return;
			}

			// Collect files in folder

			Array<wchar_t*> files;
			DirectorySearch(sourceDirectoryW, files, &arena);

			if (files.GetSize() < 0)
				return;

			// Read scripts
			MemoryBlockArena<char> currentReadFile = { 4_mB };

			Array<Module> modules;
			for (auto& file : files)
			{
				wchar_t* extension = PathFindExtensionW(file);
				if (*extension && wcscmp(extension, L".mrbuild") != 0)
					continue;

				HANDLE script = CreateFileW(file, GENERIC_READ, FILE_SHARE_READ, nullptr, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL | FILE_FLAG_SEQUENTIAL_SCAN, nullptr);
				if (script != INVALID_HANDLE_VALUE)
				{
					LARGE_INTEGER size;
					GetFileSizeEx(script, &size);

					char* allocatedBufferForScript = (char*)currentReadFile.Allocate(size.QuadPart);

					DWORD actualRead = 0;
					if (ReadFile(script, allocatedBufferForScript, (DWORD)size.QuadPart, &actualRead, nullptr))
					{
						Module module = Module::MakeModuleFromBuffer(allocatedBufferForScript);

						u32 wideNameSize = (u32)wcslen(file);
						char* narrowName = (char*)arena.Allocate(wideNameSize + 1);

						WideCharToMultiByte(CP_UTF8, 0, file, wideNameSize, narrowName, wideNameSize, nullptr, 0);
						module.path = narrowName;

						DirectorySearch(file, module.files, &arena);

						modules.Add(module);
					}
					else
					{
						MR_LOG(LogCommands, Error, "%s (%d)", *GetLastErrorString(), ::GetLastError());
					}

					CloseHandle(script);
					currentReadFile.Reset();
				}
				else
				{
					MR_LOG(LogCommands, Error, "%s", *GetLastErrorString());
				}
			}

			wchar_t* intermediateDirectoryW = (wchar_t*)arena.Allocate(intermediateDirectory.Length() * sizeof(wchar_t));
			if (!MultiByteToWideChar(CP_UTF8, 0, intermediateDirectory, intermediateDirectory.Length(), intermediateDirectoryW, intermediateDirectory.Length()))
			{
				MR_LOG(LogCommands, Error, "%s", *GetLastErrorString());
				return;
			}

			if (PathIsRelativeW(intermediateDirectoryW))
			{
				wchar_t exeLocation[MAX_PATH] = {};

				wcscpy_s(exeLocation, MAX_PATH, Commandlet::Get().GetArgs()[0]);
				PathRemoveFileSpecW(exeLocation);

				const u32 combinedDirectorySize = (u32)wcslen(exeLocation) + (u32)wcslen(intermediateDirectoryW);
				wchar_t* newDirectory = (wchar_t*)arena.Allocate((combinedDirectorySize + 10) * sizeof(wchar_t));

				PathCchCombine(newDirectory, combinedDirectorySize, exeLocation, intermediateDirectoryW);
				intermediateDirectoryW = newDirectory;
			}
			
			SHCreateDirectory(nullptr, intermediateDirectoryW);

			static MemoryBlockArena<char> moduleBuffer = { 1_mB };
			for (Module& mdl : modules)
			{
				GUID id = {};
				CoCreateGuid(&id);

				wchar_t idStr[48] = {};
				StringFromGUID2(id, idStr, 48);
				WideCharToMultiByte(CP_UTF8, 0, idStr, 48, mdl.guid, 48, nullptr, nullptr);

				wchar_t* fullPathToIntermediate = (wchar_t*)moduleBuffer.Allocate((wcslen(intermediateDirectoryW) + strlen(GetApplication()->GetApplicationCodeName()) + (mdl.moduleName.Length() * 2)) * sizeof(wchar_t));
				swprintf(fullPathToIntermediate, L"%s\\%hs\\%hs\\%hs.vcxproj", intermediateDirectoryW, GetApplication()->GetApplicationCodeName(), *mdl.moduleName, *mdl.moduleName);

				HANDLE proj = CreateFileW(fullPathToIntermediate, GENERIC_READ | GENERIC_WRITE, bIsRunningDebugMode ? FILE_SHARE_READ : 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
				if (proj != INVALID_HANDLE_VALUE)
				{
					const u32 required = (u32)snprintf(nullptr, 0, InsertVcxprojFormatSpecifier(), mdl.guid, mdl.moduleName.Chr(), mdl.moduleName.Chr(), mdl.moduleName.Chr());
					char* writeOut = (char*)moduleBuffer.Allocate(required + 1);

					snprintf(writeOut, required + 1, InsertVcxprojFormatSpecifier(), mdl.guid, mdl.moduleName.Chr(), mdl.moduleName.Chr(), mdl.moduleName.Chr());
					
					DWORD written = 0;
					WriteFile(proj, writeOut, required, &written, nullptr);
					CloseHandle(proj);
				}
				else
				{
					MR_LOG(LogPersistent, Error, "CreateFileW failed with: %s", GetLastErrorString().Chr());
				}

				moduleBuffer.Reset();
			}

			AddSolution(&modules);
		}

		QueryPerformanceCounter(&endTime);
		QueryPerformanceFrequency(&frequency);

		MR_LOG(LogCommands, Log, "Build command ran in %.2f seconds!", (endTime.QuadPart - startTime.QuadPart) / frequency.QuadPart);
	}

	void AddSolution(const Array<Module>* modules)
	{
		const String path = Commandlet::Get().Check("-sln") ? Commandlet::Get().Parse("-sln") : Commandlet::Get().Parse("-s");
		if (path.IsEmpty())
		{
			MR_LOG(LogValidator, Error, "Failed to find source/sln parameter!");
			return;
		}

		MemoryBlockArena<wchar_t> buffer = { 1_mB };

		wchar_t* convertedPath = (wchar_t*)buffer.Allocate(path.Length() * sizeof(wchar_t));
		MultiByteToWideChar(CP_UTF8, 0, path.Chr(), path.Length(), convertedPath, (path.Length() + 1) * sizeof(char));

		if (PathIsRelativeW(convertedPath))
		{
			wchar_t exeLocation[MAX_PATH] = {};

			wcscpy_s(exeLocation, MAX_PATH, Commandlet::Get().GetArgs()[0]);
			PathRemoveFileSpecW(exeLocation);

			const u32 combinedDirectorySize = (u32)wcslen(exeLocation) + (u32)wcslen(convertedPath);
			wchar_t* newDirectory = (wchar_t*)buffer.Allocate((combinedDirectorySize + 10) * sizeof(wchar_t));

			PathCchCombine(newDirectory, combinedDirectorySize, exeLocation, convertedPath);
			convertedPath = newDirectory;
		}

		PathCchRemoveFileSpec(convertedPath, wcslen(convertedPath));

		const u32 requiredFormatAmount = swprintf(nullptr, 0, L"%s\\%hs.sln", convertedPath, (*modules)[0].parent.Chr()) + 1;

		wchar_t* fullPathToSln = (wchar_t*)buffer.Allocate(requiredFormatAmount * sizeof(wchar_t));
		swprintf(fullPathToSln, requiredFormatAmount, L"%s\\%hs.sln", convertedPath, (*modules)[0].parent.Chr());

		HANDLE slnx = CreateFileW(fullPathToSln, GENERIC_READ | GENERIC_WRITE, bIsRunningDebugMode ? FILE_SHARE_READ : 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
		if (slnx != INVALID_HANDLE_VALUE)
		{
			MemoryBlockArena<char> outputFileBuffer = { 8_mB };
			MemoryBlockArena<wchar_t> pathCreating = { 1_mB };
			
			const String intermediateDir = Commandlet::Get().Parse("-i");

			wchar_t* intermediateDirectoryW = (wchar_t*)pathCreating.Allocate(intermediateDir.Length() * sizeof(wchar_t));
			if (!MultiByteToWideChar(CP_UTF8, 0, intermediateDir, intermediateDir.Length(), intermediateDirectoryW, intermediateDir.Length()))
			{
				MR_LOG(LogCommands, Error, "%s", *GetLastErrorString());
				return;
			}

			const u32 appCodeNameCount = strlen(GetApplication()->GetApplicationCodeName());
			const u32 sumOfPaths = wcslen(intermediateDirectoryW) + appCodeNameCount;
			wchar_t* pathToProductName = (wchar_t*)pathCreating.Allocate(sumOfPaths);

			wchar_t codeName[16] = {};
			MultiByteToWideChar(CP_UTF8, 0, GetApplication()->GetApplicationCodeName(), appCodeNameCount, codeName, appCodeNameCount);

			if (PathCchCombine(pathToProductName, sumOfPaths + 16, intermediateDirectoryW, codeName) != S_OK)
			{
				MR_LOG(LogValidator, Fatal, "PathCchCombine error!");
				return;
			}

			DWORD written = 0;
			WriteFile(slnx, InsertSlnxHeaderFormatSpecifier(), strlen(InsertSlnxHeaderFormatSpecifier()), &written, nullptr);

			for (auto& mdl : *modules)
			{
				const u32 requiredAmountToFormat = snprintf(nullptr, 0, "\nProject(\"{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}\") = \"%s\", \"%ls\\%s\\%s.vcxproj\", \"%s\"\nEndProject", mdl.moduleName.Chr(), pathToProductName, mdl.moduleName.Chr(), mdl.moduleName.Chr(), mdl.guid) + 1;
				char* lineBuffer = (char*)outputFileBuffer.Allocate(requiredAmountToFormat);

				snprintf(lineBuffer, requiredAmountToFormat, "\nProject(\"{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}\") = \"%s\", \"%ls\\%s\\%s.vcxproj\", \"%s\"\nEndProject", mdl.moduleName.Chr(), pathToProductName, mdl.moduleName.Chr(), mdl.moduleName.Chr(), mdl.guid);

				WriteFile(slnx, lineBuffer, requiredAmountToFormat - 1, &written, nullptr);

#ifdef MR_DEBUG
				if (written > 256) FlushFileBuffers(slnx);
#endif // MR_DEBUG
			}

			constexpr const char preSolutions[] =
				"\nGlobal\n"
				"	GlobalSection(SolutionConfigurationPlatforms) = preSolution\n"
				"		Debug|x64 = Debug|x64\n"
				"		Development|x64 = Development|x64\n"
				"		Shipping|x64 = Shipping|x64\n"
				"	EndGlobalSection\n";


			WriteFile(slnx, preSolutions, sizeof(preSolutions) / sizeof(preSolutions[0]), &written, nullptr);

			constexpr const char openProjectConfigurationPlatforms[] = "	GlobalSection(ProjectConfigurationPlatforms) = postSolution";
			WriteFile(slnx, openProjectConfigurationPlatforms, sizeof(openProjectConfigurationPlatforms) / sizeof(openProjectConfigurationPlatforms[0]), &written, nullptr);

			for (auto& mdl : *modules)
			{
				constexpr const char activeCfgTemplate[] =
					"\n\t\t%s.Debug|x64.ActiveCfg = Debug|x64"
					"\n\t\t%s.Debug|x64.Build.0 = Debug|x64"
					"\n\t\t%s.Development|x64.ActiveCfg = Development|x64"
					"\n\t\t%s.Development|x64.Build.0 = Development|x64"
					"\n\t\t%s.Shipping|x64.ActiveCfg = Shipping|x64"
					"\n\t\t%s.Shipping|x64.Build.0 = Shipping|x64";

				const u32 requiredAmountToFormat = snprintf(nullptr, 0, activeCfgTemplate, mdl.guid, mdl.guid, mdl.guid, mdl.guid, mdl.guid, mdl.guid) + 1;
				char* lineBuffer = (char*)outputFileBuffer.Allocate(requiredAmountToFormat);

				snprintf(lineBuffer, requiredAmountToFormat, activeCfgTemplate, mdl.guid, mdl.guid, mdl.guid, mdl.guid, mdl.guid, mdl.guid);

				WriteFile(slnx, lineBuffer, requiredAmountToFormat, &written, nullptr);

#ifdef MR_DEBUG
				FlushFileBuffers(slnx);
#endif // MR_DEBUG
			}

			constexpr const char closeProjectConfigurationPlatforms[] = "\n\tEndGlobalSection\n";
			WriteFile(slnx, closeProjectConfigurationPlatforms, sizeof(closeProjectConfigurationPlatforms) / sizeof(closeProjectConfigurationPlatforms[0]), &written, nullptr);

			GUID id = {};
			CoCreateGuid(&id);

			wchar_t idStr[48] = {};
			StringFromGUID2(id, idStr, 48);

			constexpr const char finalSolutionProperties[] =
				"	GlobalSection(SolutionProperties) = preSolution\n"
				"		HideSolutionNode = FALSE\n"
				"	EndGlobalSection\n"
				"	GlobalSection(ExtensibilityGlobals) = postSolution\n"
				"		SolutionGuid = %ls\n"
				"	EndGlobalSection\n"
				"EndProject";

			const u32 requiredAmountToFormat = snprintf(nullptr, 0, finalSolutionProperties, idStr) + 1;
			char* lineBuffer = (char*)outputFileBuffer.Allocate(requiredAmountToFormat);

			snprintf(lineBuffer, requiredAmountToFormat, finalSolutionProperties, idStr);

			WriteFile(slnx, lineBuffer, requiredAmountToFormat - 1, &written, nullptr);
			CloseHandle(slnx);
		}
	}
}
