/* Copyright 2020 - 2026, Hansson Software. All rights reserved. */

#include "Commands.h"
#include "CommandRegistry.h"

#include <Commandlet.h>


#include <Platform/Winapi.h>
#include <Shlwapi.h>
#include <PathCch.h>
#include <Application/Application.h>

#pragma warning(disable : 6387)
#pragma warning(disable : 6031)

LOG_ADDCATEGORY(Commands);
LOG_ADDCATEGORY(Build);
LOG_ADDCATEGORY(Validator);

namespace Commands
{
	ADD_NEW_BUILD_COMMAND("-make", "Generates project files", Generate_Cmd);

	inline constexpr const char* InsertVcxprojFormatSpecifier()
	{
		constexpr const char* vcxprojTemplate = R"XML(<!-- Generated by MeteorBuild(R) -->
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Development|x64">
      <Configuration>Development</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Shipping|x64">
      <Configuration>Shipping</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>

  <PropertyGroup Label="Globals">
    <VCProjectVersion>18.0</VCProjectVersion>
    <ProjectGuid>%s</ProjectGuid>
    <Keyword>Win32Proj</Keyword>
  </PropertyGroup>

  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration">
    <ConfigurationType>Makefile</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>v145</PlatformToolset>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Development|x64'" Label="Configuration">
    <ConfigurationType>Makefile</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>v145</PlatformToolset>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Shipping|x64'" Label="Configuration">
    <ConfigurationType>Makefile</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
    <PlatformToolset>v145</PlatformToolset>
  </PropertyGroup>

  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings"></ImportGroup>
  <ImportGroup Label="Shared"></ImportGroup>

  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Development|x64'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Shipping|x64'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>

  <PropertyGroup Label="UserMacros" />

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <NMakeBuildCommandLine>$(ProductDir)MeteorBuild.exe -build -c $(Configuration)</NMakeBuildCommandLine>
    <NMakeOutput>%s.dll</NMakeOutput>
    <NMakePreprocessorDefinitions>MR_DEBUG;$(NMakePreprocessorDefinitions)</NMakePreprocessorDefinitions>
    <NMakeReBuildCommandLine>$(ProductDir)MeteorBuild.exe -rebuild -c $(Configuration)</NMakeReBuildCommandLine>
    <NMakeCleanCommandLine>$(ProductDir)MeteorBuild.exe -clean -c $(Configuration)</NMakeCleanCommandLine>
    <NMakeIncludeSearchPath>%s</NMakeIncludeSearchPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Development|x64'">
    <NMakeBuildCommandLine>$(ProductDir)MeteorBuild.exe -build -c $(Configuration)</NMakeBuildCommandLine>
    <NMakeOutput>%s.dll</NMakeOutput>
    <NMakePreprocessorDefinitions>MR_DEBUG;$(NMakePreprocessorDefinitions)</NMakePreprocessorDefinitions>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Shipping|x64'">
    <NMakeBuildCommandLine>$(ProductDir)MeteorBuild.exe -build -c $(Configuration)</NMakeBuildCommandLine>
    <NMakeOutput>%s.dll</NMakeOutput>
    <NMakePreprocessorDefinitions>$(NMakePreprocessorDefinitions)</NMakePreprocessorDefinitions>
  </PropertyGroup>

  <ItemGroup></ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets"></ImportGroup>

</Project>)XML";

		return vcxprojTemplate;
	}

	inline constexpr const char* InsertSlnxHeaderFormatSpecifier()
	{
		constexpr const char* slnxTemplate =
R"XML(<Solution>
<Configurations>
    <Platform Name="x64" />
  </Configurations>)XML";
		return slnxTemplate;
	}

	inline constexpr const char* InsertSlnxFooterSpecifier()
	{
		constexpr const char* slnxTemplate =
			"\n</Solution>";
		return slnxTemplate;
	}

	void Generate_Cmd()
	{
		LARGE_INTEGER startTime, endTime, frequency;
		QueryPerformanceCounter(&startTime);

		const String sourceDirectory = Commandlet::Get().Parse("-s");
		const String intermediateDirectory = Commandlet::Get().Parse("-i");

		// Arena allocates bytes, so equal size will be allocated!
		// WChar: 32 MB (Char / 2)
		// Char: 32 MB

#ifdef MR_PLATFORM_WINDOWS
		static MemoryBlockArena<wchar_t> arena = { 16 * 1024 * 1024 };
#else
		static MemoryBlockArena<char> arena = { 16 * 1024 * 1024 };
#endif // MR_PLATFORM_WINDOWS

		if (sourceDirectory && intermediateDirectory)
		{
			wchar_t* sourceDirectoryW = (wchar_t*)arena.Allocate(sourceDirectory.Length() * sizeof(wchar_t));
			if (!MultiByteToWideChar(CP_UTF8, 0, sourceDirectory, sourceDirectory.Length(), sourceDirectoryW, sourceDirectory.Length()))
			{
				MR_LOG(LogCommands, Error, "%s", *GetLastErrorString());
				return;
			}

			// Collect files in folder

			Array<wchar_t*> files;
			DirectorySearch(sourceDirectoryW, files, &arena);

			if (files.GetSize() < 0)
				return;

			// Read scripts
			MemoryBlockArena<char> currentReadFile = { 8 * 1024 * 1024 };

			Array<Module> modules;
			for (auto& file : files)
			{
				wchar_t* extension = PathFindExtensionW(file);
				if (*extension && wcscmp(extension, L".mrbuild") != 0)
					continue;

				HANDLE script = CreateFileW(file, GENERIC_READ, FILE_SHARE_READ, nullptr, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL | FILE_FLAG_SEQUENTIAL_SCAN, nullptr);
				if (script != INVALID_HANDLE_VALUE)
				{
					LARGE_INTEGER size;
					GetFileSizeEx(script, &size);

					char* allocatedBufferForScript = (char*)currentReadFile.Allocate(size.QuadPart);

					DWORD actualRead = 0;
					if (ReadFile(script, allocatedBufferForScript, (DWORD)size.QuadPart, &actualRead, nullptr))
					{
						Module module = Module::MakeModuleFromBuffer(allocatedBufferForScript);

						u32 wideNameSize = (u32)wcslen(file);
						char* narrowName = (char*)arena.Allocate(wideNameSize + 1);

						WideCharToMultiByte(CP_UTF8, 0, file, wideNameSize, narrowName, wideNameSize, nullptr, 0);
						module.path = narrowName;

						DirectorySearch(file, module.files, &arena);

						modules.Add(module);
					}
					else
					{
						MR_LOG(LogCommands, Error, "%s (%d)", *GetLastErrorString(), ::GetLastError());
					}

					CloseHandle(script);
					currentReadFile.Reset();
				}
				else
				{
					MR_LOG(LogCommands, Error, "%s", *GetLastErrorString());
				}
			}

			wchar_t* intermediateDirectoryW = (wchar_t*)arena.Allocate(intermediateDirectory.Length() * sizeof(wchar_t));
			if (!MultiByteToWideChar(CP_UTF8, 0, intermediateDirectory, intermediateDirectory.Length(), intermediateDirectoryW, intermediateDirectory.Length()))
			{
				MR_LOG(LogCommands, Error, "%s", *GetLastErrorString());
				return;
			}

			if (PathIsRelativeW(intermediateDirectoryW))
			{
				wchar_t exeLocation[MAX_PATH] = {};

				wcscpy_s(exeLocation, MAX_PATH, Commandlet::Get().GetArgs()[0]);
				PathRemoveFileSpecW(exeLocation);

				const u32 combinedDirectorySize = (u32)wcslen(exeLocation) + (u32)wcslen(intermediateDirectoryW);
				wchar_t* newDirectory = (wchar_t*)arena.Allocate((combinedDirectorySize + 10) * sizeof(wchar_t));

				PathCchCombine(newDirectory, combinedDirectorySize, exeLocation, intermediateDirectoryW);
				intermediateDirectoryW = newDirectory;
			}
			
			static MemoryBlockArena<char> moduleBuffer = { 1_mB };
			for (Module& mdl : modules)
			{
				GUID id = {};
				CoCreateGuid(&id);

				wchar_t idStr[48] = {};
				StringFromGUID2(id, idStr, 48);
				WideCharToMultiByte(CP_UTF8, 0, idStr, 48, mdl.guid, 48, nullptr, nullptr);

				wchar_t* fullPathToIntermediate = (wchar_t*)moduleBuffer.Allocate((wcslen(intermediateDirectoryW) + strlen(GetApplication()->GetApplicationCodeName()) + (mdl.moduleName.Length() * 2)) * sizeof(wchar_t));
				swprintf(fullPathToIntermediate, L"%s\\%hs\\%hs\\%hs.vcxproj", intermediateDirectoryW, GetApplication()->GetApplicationCodeName(), *mdl.moduleName, *mdl.moduleName);

				HANDLE proj = CreateFileW(fullPathToIntermediate, GENERIC_READ | GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
				if (proj != INVALID_HANDLE_VALUE)
				{
					const u32 required = (u32)snprintf(nullptr, 0, InsertVcxprojFormatSpecifier(), mdl.guid, mdl.moduleName.Chr(), mdl.moduleName.Chr(), mdl.moduleName.Chr());
					char* writeOut = (char*)moduleBuffer.Allocate(required + 1);

					snprintf(writeOut, required + 1, InsertVcxprojFormatSpecifier(), mdl.guid, mdl.moduleName.Chr(), mdl.moduleName.Chr(), mdl.moduleName.Chr());
					
					DWORD written = 0;
					WriteFile(proj, writeOut, required, &written, nullptr);
					CloseHandle(proj);
				}

				moduleBuffer.Reset();
			}

			AddSolution(&modules);
		}

		QueryPerformanceCounter(&endTime);
		QueryPerformanceFrequency(&frequency);

		MR_LOG(LogCommands, Log, "Build command ran in %.4f seconds!", (endTime.QuadPart - startTime.QuadPart) / frequency.QuadPart);
	}

	void AddSolution(const Array<Module>* modules)
	{
		const String path = Commandlet::Get().Check("-sln") ? Commandlet::Get().Parse("-sln") : Commandlet::Get().Parse("-s");
		if (path.IsEmpty())
		{
			MR_LOG(LogValidator, Error, "Failed to find source/sln parameter!");
			return;
		}

		MemoryBlockArena<wchar_t> buffer = { 1_mB };

		wchar_t* convertedPath = (wchar_t*)buffer.Allocate(path.Length() * sizeof(wchar_t));
		MultiByteToWideChar(CP_UTF8, 0, path.Chr(), path.Length(), convertedPath, (path.Length() + 1) * sizeof(char));

		if (PathIsRelativeW(convertedPath))
		{
			wchar_t exeLocation[MAX_PATH] = {};

			wcscpy_s(exeLocation, MAX_PATH, Commandlet::Get().GetArgs()[0]);
			PathRemoveFileSpecW(exeLocation);

			const u32 combinedDirectorySize = (u32)wcslen(exeLocation) + (u32)wcslen(convertedPath);
			wchar_t* newDirectory = (wchar_t*)buffer.Allocate((combinedDirectorySize + 10) * sizeof(wchar_t));

			PathCchCombine(newDirectory, combinedDirectorySize, exeLocation, convertedPath);
			convertedPath = newDirectory;
		}

		PathCchRemoveFileSpec(convertedPath, wcslen(convertedPath));

		const u32 requiredFormatAmount = swprintf(nullptr, 0, L"%s\\%hs.slnx", convertedPath, (*modules)[0].parent.Chr()) + 1;

		wchar_t* fullPathToSln = (wchar_t*)buffer.Allocate(requiredFormatAmount * sizeof(wchar_t));
		swprintf(fullPathToSln, requiredFormatAmount, L"%s\\%hs.slnx", convertedPath, (*modules)[0].parent.Chr());

		HANDLE slnx = CreateFileW(fullPathToSln, GENERIC_READ | GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
		if (slnx != INVALID_HANDLE_VALUE)
		{
			MemoryBlockArena<char> outputFileBuffer = { 8_mB };
			MemoryBlockArena<wchar_t> pathCreating = { 1_mB };
			
			const String intermediateDir = Commandlet::Get().Parse("-i");

			wchar_t* intermediateDirectoryW = (wchar_t*)pathCreating.Allocate(intermediateDir.Length() * sizeof(wchar_t));
			if (!MultiByteToWideChar(CP_UTF8, 0, intermediateDir, intermediateDir.Length(), intermediateDirectoryW, intermediateDir.Length()))
			{
				MR_LOG(LogCommands, Error, "%s", *GetLastErrorString());
				return;
			}

			const u32 appCodeNameCount = strlen(GetApplication()->GetApplicationCodeName());
			const u32 sumOfPaths = wcslen(intermediateDirectoryW) + appCodeNameCount;
			wchar_t* pathToProductName = (wchar_t*)pathCreating.Allocate(sumOfPaths);

			wchar_t codeName[16] = {};
			MultiByteToWideChar(CP_UTF8, 0, GetApplication()->GetApplicationCodeName(), appCodeNameCount, codeName, appCodeNameCount);

			if (PathCchCombine(pathToProductName, sumOfPaths + 16, intermediateDirectoryW, codeName) != S_OK)
			{
				MR_LOG(LogValidator, Fatal, "PathCchCombine error!");
				return;
			}

			DWORD written = 0;
			WriteFile(slnx, InsertSlnxHeaderFormatSpecifier(), 77, &written, nullptr);

			char* appendedProjects = nullptr;
			for (auto& mdl : *modules)
			{
				const u32 requiredAmountToFormat = swprintf(nullptr, 0, L"%s\\%hs\\%hs.vcxproj", pathToProductName, mdl.moduleName.Chr(), mdl.moduleName.Chr()) + 1;
				wchar_t* pathBuffer = (wchar_t*)pathCreating.Allocate((requiredAmountToFormat + 1) * sizeof(wchar_t));
				swprintf(pathBuffer, requiredAmountToFormat, L"%s\\%hs\\%hs.vcxproj", pathToProductName, mdl.moduleName.Chr(), mdl.moduleName.Chr());

				char id[40] = {};
				strncpy(id, mdl.guid + 1, 36);

				const u32 lines = snprintf(nullptr, 0, "\n  <Project Path=\"%ls\" Id=\"%s\"/>", pathBuffer, id) + 1;
				char* lineBuffer = (char*)outputFileBuffer.Allocate(lines);

				const u32 made = snprintf(lineBuffer, lines, "\n  <Project Path=\"%ls\" Id=\"%s\"/>", pathBuffer, id) + 1;
				WriteFile(slnx, lineBuffer, made, &written, nullptr);
			}

			WriteFile(slnx, InsertSlnxFooterSpecifier(), 12, &written, nullptr);
			CloseHandle(slnx);
		}
	}
}
