/* Copyright 2020 - 2026, Hansson Software. All rights reserved. */

#include "VisualStudioProject.h"
#include <Logging/Log.h>
#include <Core/Utils.h>
#include <Types/Array.h>
#include <Types/String.h>

#include <Platform/Winapi.h>

LOG_ADDCATEGORY(VisualStudioStaticClass);

void VisualStudioStaticClass::GeneratePropertySheetsBoilerplateCode(HANDLE fileHandle)
{
	constexpr const char boilerplateProps[] =
		"\t<Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.props\" />"
		"\t\t<ImportGroup Label=\"ExtensionSettings\">"
		"\t</ImportGroup>"
		"\t<ImportGroup Label=\"Shared\">"
		"\t</ImportGroup>";

	constexpr const u32 size = (sizeof(boilerplateProps) / sizeof(boilerplateProps[0])) - 1;

	DWORD written = 0;
	if (!WriteFile(fileHandle, boilerplateProps, size, &written, nullptr))
	{
		MR_LOG(LogVisualStudioStaticClass, Fatal, "Failed to write boilerplate code! (%d)  %s", ::GetLastError(), *Utils::GetError());
	}

	constexpr const char boilerplateConfigurationTypes[] =
		"\t<ImportGroup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">\n"
		"\t\t<Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\n"
		"\t</ImportGroup>"
		"\t<ImportGroup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Test|x64'\">\n"
		"\t\t<Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\n"
		"\t</ImportGroup>"
		"\t<ImportGroup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Shipping|x64'\">\n"
		"\t\t<Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\n"
		"\t</ImportGroup>";

	constexpr const u32 boilerplateConfigurationTypesSize = (sizeof(boilerplateConfigurationTypes) / sizeof(boilerplateConfigurationTypes[0])) - 1;

	if (!WriteFile(fileHandle, boilerplateConfigurationTypes, boilerplateConfigurationTypesSize, &written, nullptr))
	{
		MR_LOG(LogVisualStudioStaticClass, Fatal, "Failed to write boilerplate code! (%d)  %s", ::GetLastError(), *Utils::GetError());
	}

	//for (const IDEConfiguration& config : *configs)
	//{
	//	if (config.configurationName)
	//	{
	//		char bigEnoughBuffer[512] = {};

	//		const u32 configNameSize = (u32)strlen(config.configurationName);

	//		snprintf(bigEnoughBuffer, boilerplatePrintfSize + configNameSize, boilerplatePrintf, config.configurationName);

	//		if (!WriteFile(file, boilerplateConstant, size, &written, nullptr))
	//		{
	//			MR_LOG(LogVcxprojGen, Fatal, "Failed to write boilerplate code! (%d)  %s", ::GetLastError(), *Utils::GetError());
	//			break;
	//		}
	//		
	//		continue;
	//	}
	//		
	//	MR_LOG(LogVcxprojGen, Fatal, "Invalid config name!");
	//}
}

void VisualStudioStaticClass::GenerateFirstLinesOfBoilerplateCode(HANDLE fileHandle)
{
	constexpr const char autogeneratedTextAndFirstProjectLine[] =
		"<!-- This file is generated with MeteorBuild(R) -->\n\n"
		"<Project DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\n"
		"\t<ItemGroup Label=\"ProjectConfigurations\">\n"
		"\t\t<ProjectConfiguration Include=\"Debug|x64\">\n"
		"\t\t\t<Configuration>Debug</Configuration>\n"
		"\t\t\t<Platform>x64</Platform>\n"
		"\t\t</ProjectConfiguration>\n"
		"\t\t<ProjectConfiguration Include=\"Test|x64\">\n"
		"\t\t\t<Configuration>Test</Configuration>\n"
		"\t\t\t<Platform>x64</Platform>\n"
		"\t\t</ProjectConfiguration>\n"
		"\t\t<ProjectConfiguration Include=\"Shipping|x64\">\n"
		"\t\t\t<Configuration>Shipping</Configuration>\n"
		"\t\t\t<Platform>x64</Platform>\n"
		"\t\t</ProjectConfiguration>\n"
		"\t</ItemGroup>\n";

	constexpr const u32 autogeneratedTextAndFirstProjectLineSize = (sizeof(autogeneratedTextAndFirstProjectLine) / sizeof(autogeneratedTextAndFirstProjectLine[0])) - 1;

	DWORD written = 0;
	if (!WriteFile(fileHandle, autogeneratedTextAndFirstProjectLine, autogeneratedTextAndFirstProjectLineSize, &written, nullptr))
	{
		MR_LOG(LogVisualStudioStaticClass, Fatal, "Failed to write boilerplate code! (%d)  %s", ::GetLastError(), *Utils::GetError());
	}
}

void VisualStudioStaticClass::GenerateClosingBoilerplateCode(HANDLE fileHandle)
{
	constexpr const char autogeneratedTextAndFirstProjectLine[] =
		"</Project>";
	constexpr const u32 autogeneratedTextAndFirstProjectLineSize = sizeof(autogeneratedTextAndFirstProjectLine) / sizeof(autogeneratedTextAndFirstProjectLine[0]);

	DWORD written = 0;
	if (!WriteFile(fileHandle, autogeneratedTextAndFirstProjectLine, autogeneratedTextAndFirstProjectLineSize, &written, nullptr))
	{
		MR_LOG(LogVisualStudioStaticClass, Fatal, "Failed to write boilerplate code! (%d)  %s", ::GetLastError(), *Utils::GetError());
	}
}

void VisualStudioStaticClass::GenerateDynamicDetailsForIdentification(HANDLE fileHandle, const String* moduleName, const char* guid)
{
	constexpr const char dynamicGroup[] =
		"\t<PropertyGroup Label=\"Globals\">\n"
		"\t\t<VCProjectVersion>18.0</VCProjectVersion>\n"
		"\t\t<Keyword>Win32Proj</Keyword>\n"
		"\t\t<ProjectGuid>%s</ProjectGuid>\n"
		"\t\t<RootNamespace>%s</RootNamespace>\n"
		"\t\t<WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>\n"
		"\t\t<ProjectName>%s</ProjectName>\n"
		"\t</PropertyGroup>\n";

	char buffer[sizeof(dynamicGroup) / sizeof(dynamicGroup[0]) + 256] = {};

	const u32 actualSize = snprintf(nullptr, 0, dynamicGroup, guid, moduleName->Chr(), moduleName->Chr());
	snprintf(buffer, actualSize, dynamicGroup, guid, moduleName->Chr(), moduleName->Chr());

	DWORD written = 0;
	if (!WriteFile(fileHandle, buffer, actualSize, &written, nullptr))
	{
		MR_LOG(LogVisualStudioStaticClass, Fatal, "Failed to write dynamic code! (%d)  %s", ::GetLastError(), *Utils::GetError());
	}
}

void VisualStudioStaticClass::GenerateConfigurationDetails(HANDLE fileHandle)
{
	constexpr const char configurationParts[] =
		"\t<Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.Default.props\" />\n";
		"\t<PropertyGroup Condition=\"\'$(Configuration)|$(Platform)\'==\'Debug|x64\'\" Label=\"Configuration\">\n"
		"\t\t<ConfigurationType>DynamicLibrary</ConfigurationType>\n"
		"\t\t<UseDebugLibraries>true</UseDebugLibraries>\n"
		"\t\t<PlatformToolset>v145</PlatformToolset>\n"
		"\t\t<CharacterSet>Unicode</CharacterSet>\n"
		"\t</PropertyGroup>\n"
		"\t<PropertyGroup Condition=\"\'$(Configuration)|$(Platform)\'==\'Test|x64\'\" Label=\"Configuration\">\n"
		"\t\t<ConfigurationType>DynamicLibrary</ConfigurationType>\n"
		"\t\t<UseDebugLibraries>true</UseDebugLibraries>\n"
		"\t\t<PlatformToolset>v145</PlatformToolset>\n"
		"\t\t<CharacterSet>Unicode</CharacterSet>\n"
		"\t</PropertyGroup>\n"
		"\t<PropertyGroup Condition=\"\'$(Configuration)|$(Platform)\'==\'Shipping|x64\'\" Label=\"Configuration\">\n"
		"\t\t<ConfigurationType>DynamicLibrary</ConfigurationType>\n"
		"\t\t<PlatformToolset>v145</PlatformToolset>\n"
		"\t\t<CharacterSet>Unicode</CharacterSet>\n"
		"\t</PropertyGroup>\n";

	constexpr const u32 configurationPartsSize = (sizeof(configurationParts) / sizeof(configurationParts[0])) - 1;


	DWORD written = 0;
	if (!WriteFile(fileHandle, configurationParts, configurationPartsSize, &written, nullptr))
	{
		MR_LOG(LogVisualStudioStaticClass, Fatal, "Failed to write dynamic code! (%d)  %s", ::GetLastError(), *Utils::GetError());
	}
}
