/* Copyright 2020 - 2026, Hansson Software. All rights reserved. */

#include "VisualStudioProject.h"
#include <Logging/Log.h>
#include <Core/Utils.h>
#include <Types/Array.h>

#include <Platform/Winapi.h>

LOG_ADDCATEGORY(VisualStudioStaticClass);

void VisualStudioStaticClass::GeneratePropertySheetsBoilerplateCode(HANDLE fileHandle)
{
	constexpr const char boilerplateProps[] =
		"\t<Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.props\" />"
		"\t\t<ImportGroup Label=\"ExtensionSettings\">"
		"\t</ImportGroup>"
		"\t<ImportGroup Label=\"Shared\">"
		"\t</ImportGroup>";

	constexpr const u32 size = sizeof(boilerplateProps) / sizeof(boilerplateProps[0]);

	DWORD written = 0;
	if (!WriteFile(fileHandle, boilerplateProps, size, &written, nullptr))
	{
		MR_LOG(LogVisualStudioStaticClass, Fatal, "Failed to write boilerplate code! (%d)  %s", ::GetLastError(), *Utils::GetError());
	}

	constexpr const char boilerplateConfigurationTypes[] =
		"\t<ImportGroup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">\n"
		"\t\t<Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\n"
		"\t</ImportGroup>"
		"\t<ImportGroup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Test|x64'\">\n"
		"\t\t<Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\n"
		"\t</ImportGroup>"
		"\t<ImportGroup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Shipping|x64'\">\n"
		"\t\t<Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\n"
		"\t</ImportGroup>";

	constexpr const u32 boilerplateConfigurationTypesSize = sizeof(boilerplateConfigurationTypes) / sizeof(boilerplateConfigurationTypes[0]);

	if (!WriteFile(fileHandle, boilerplateConfigurationTypes, boilerplateConfigurationTypesSize, &written, nullptr))
	{
		MR_LOG(LogVisualStudioStaticClass, Fatal, "Failed to write boilerplate code! (%d)  %s", ::GetLastError(), *Utils::GetError());
	}

	//for (const IDEConfiguration& config : *configs)
	//{
	//	if (config.configurationName)
	//	{
	//		char bigEnoughBuffer[512] = {};

	//		const u32 configNameSize = (u32)strlen(config.configurationName);

	//		snprintf(bigEnoughBuffer, boilerplatePrintfSize + configNameSize, boilerplatePrintf, config.configurationName);

	//		if (!WriteFile(file, boilerplateConstant, size, &written, nullptr))
	//		{
	//			MR_LOG(LogVcxprojGen, Fatal, "Failed to write boilerplate code! (%d)  %s", ::GetLastError(), *Utils::GetError());
	//			break;
	//		}
	//		
	//		continue;
	//	}
	//		
	//	MR_LOG(LogVcxprojGen, Fatal, "Invalid config name!");
	//}
}

void VisualStudioStaticClass::GenerateFirstLinesOfBoilerplateCode(HANDLE fileHandle)
{
	constexpr const char autogeneratedTextAndFirstProjectLine[] = 
		"<!-- This file is generated with MeteorBuild(R) -->\n\n"
		"<Project DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\n";
	constexpr const u32 autogeneratedTextAndFirstProjectLineSize = (sizeof(autogeneratedTextAndFirstProjectLine) / sizeof(autogeneratedTextAndFirstProjectLine[0])) - 1;

	DWORD written = 0;
	if (!WriteFile(fileHandle, autogeneratedTextAndFirstProjectLine, autogeneratedTextAndFirstProjectLineSize, &written, nullptr))
	{
		MR_LOG(LogVisualStudioStaticClass, Fatal, "Failed to write boilerplate code! (%d)  %s", ::GetLastError(), *Utils::GetError());
	}
}

void VisualStudioStaticClass::GenerateClosingBoilerplateCode(HANDLE fileHandle)
{
	constexpr const char autogeneratedTextAndFirstProjectLine[] =
		"</Project>";
	constexpr const u32 autogeneratedTextAndFirstProjectLineSize = sizeof(autogeneratedTextAndFirstProjectLine) / sizeof(autogeneratedTextAndFirstProjectLine[0]);

	DWORD written = 0;
	if (!WriteFile(fileHandle, autogeneratedTextAndFirstProjectLine, autogeneratedTextAndFirstProjectLineSize, &written, nullptr))
	{
		MR_LOG(LogVisualStudioStaticClass, Fatal, "Failed to write boilerplate code! (%d)  %s", ::GetLastError(), *Utils::GetError());
	}
}
