/* Copyright 2020 - 2026, Hansson Software. All rights reserved. */

#pragma once
#include <HAL/DataTypes.h>
#include <Logging/Log.h>

namespace Project
{
	inline constexpr const char Configurations[] =
		"<!-- Generated by MeteorBuild(R) -->\n"
		"<Project DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\n"
		" <ItemGroup Label=\"ProjectConfigurations\">\n"

		"  <ProjectConfiguration Include=\"Debug|x64\">\n"
		"   <Configuration>Debug</Configuration>\n"
		"   <Platform>x64</Platform>\n"
		"  </ProjectConfiguration>\n"
		"  <ProjectConfiguration Include=\"Development|x64\">\n"
		"   <Configuration>Development</Configuration>\n"
		"   <Platform>x64</Platform>\n"
		"  </ProjectConfiguration>\n"
		"  <ProjectConfiguration Include=\"Shipping|x64\">\n"
		"   <Configuration>Shipping</Configuration>\n"
		"   <Platform>x64</Platform>\n"
		"  </ProjectConfiguration>\n"
		" </ItemGroup>\n";

	inline constexpr const char ProjectIdentification[] =
		" <PropertyGroup Label=\"Globals\">\n"
		"  <VCProjectVersion>18.0</VCProjectVersion>\n"
		"  <Keyword>Win32Proj</Keyword>\n"
		"  <ProjectGuid>%s</ProjectGuid>\n"
		" </PropertyGroup>\n";

	inline constexpr const char PropertyGroups[] =
		" <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.Default.props\"/>\n"
		" <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\" Label=\"Configuration\">\n"
		"  <ConfigurationType>Makefile</ConfigurationType>\n"
		"  <UseDebugLibraries>true</UseDebugLibraries>\n"
		"  <PlatformToolset>v145</PlatformToolset>\n"
		" </PropertyGroup>\n"
		" <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Development|x64'\" Label=\"Configuration\">\n"
		"  <ConfigurationType>Makefile</ConfigurationType>\n"
		"  <UseDebugLibraries>true</UseDebugLibraries>\n"
		"  <PlatformToolset>v145</PlatformToolset>\n"
		" </PropertyGroup>\n"
		" <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Shipping|x64'\" Label=\"Configuration\">\n"
		"  <ConfigurationType>Makefile</ConfigurationType>\n"
		"  <UseDebugLibraries>false</UseDebugLibraries>\n"
		"  <PlatformToolset>v145</PlatformToolset>\n"
		"  <WholeProgramOptimization>true</WholeProgramOptimization>\n"
		" </PropertyGroup>\n"
		" <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.props\" />\n"
		" <ImportGroup Label=\"ExtensionSettings\">\n"
		" </ImportGroup>\n"
		" <ImportGroup Label=\"Shared\">\n"
		" </ImportGroup>\n"
		" <ImportGroup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">\n"
		"  <Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\n"
		" </ImportGroup>\n"
		" <ImportGroup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Development|x64'\">\n"
		"  <Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\n"
		" </ImportGroup>\n"
		" <ImportGroup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Shipping|x64'\">\n"
		"  <Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\n"
		" </ImportGroup>\n";

	inline constexpr const char Macros[] =
		" <PropertyGroup Label=\"UserMacros\">\n"
		"  <ProductDir>$(SolutionDir)product\\</ProductDir>\n"
		"  <ModuleDir>$(SolutionDir)engine\\%s\\</ModuleDir>\n"
		" </PropertyGroup>\n";

	inline constexpr const char* EntryFormat(u64 hashedExtensionValue)
	{
		switch (hashedExtensionValue)
		{
		case 3091167709698109830: // .cpp
			return "  <ClCompile Include=\"%ls\" />\n";

		case 565857095260348859: // .h
			return "  <ClInclude Include=\"%ls\" />\n";

		case 9301237637030385942: // .natvis
			return "  <Natvis Include=\"%ls\" />\n";

		case 0:
			MR_ASSERT(false, "Project::FileExtension::resource");
			return "  <None Include=\"%ls\" />\n";

		default:
			return "  <None Include=\"%ls\" />\n";
		}

		return "  <None Include=\"%ls\" />\n";
	}

	inline constexpr const char ConfigurationDependentSettings[] =
		" <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|x64'\">\n"
		"  <NMakeBuildCommandLine>$(ProductDir)MeteorBuild.exe -build -c $(Configuration) -m $(ProjectName)</NMakeBuildCommandLine>\n"
		"  <NMakeReBuildCommandLine>$(ProductDir)MeteorBuild.exe -rebuild -c $(Configuration) -m $(ProjectName)</NMakeReBuildCommandLine>\n"
		"  <NMakeCleanCommandLine>$(ProductDir)MeteorBuild.exe -clean -c $(Configuration) -m $(ProjectName)</NMakeCleanCommandLine>\n"
		"  <NMakeOutput>%s.dll</NMakeOutput>\n"
		"  <NMakePreprocessorDefinitions>MR_DEBUG;MR_%s_EXPORT;$(NMakePreprocessorDefinitions)</NMakePreprocessorDefinitions>\n"
		"  <NMakeIncludeSearchPath>%s</NMakeIncludeSearchPath>\n"
		"  <ExecutablePath>$(ProductDir);$(ExecutablePath)</ExecutablePath>\n"
		" </PropertyGroup>\n"
		" <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Development|x64'\">\n"
		"  <NMakeBuildCommandLine>$(ProductDir)MeteorBuild.exe -build -c $(Configuration) -m $(ProjectName)</NMakeBuildCommandLine>\n"
		"  <NMakeReBuildCommandLine>$(ProductDir)MeteorBuild.exe -rebuild -c $(Configuration) -m $(ProjectName)</NMakeReBuildCommandLine>\n"
		"  <NMakeCleanCommandLine>$(ProductDir)MeteorBuild.exe -clean -c $(Configuration) -m $(ProjectName)</NMakeCleanCommandLine>\n"
		"  <NMakeOutput>%s.dll</NMakeOutput>\n"
		"  <NMakePreprocessorDefinitions>MR_DEBUG;MR_%s_EXPORT;$(NMakePreprocessorDefinitions)</NMakePreprocessorDefinitions>\n"
		"  <NMakeIncludeSearchPath>%s</NMakeIncludeSearchPath>\n"
		"  <ExecutablePath>$(ProductDir);$(ExecutablePath)</ExecutablePath>\n"
		" </PropertyGroup>\n"
		" <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Shipping|x64'\">\n"
		"  <NMakeBuildCommandLine>$(ProductDir)MeteorBuild.exe -build -c $(Configuration) -m $(ProjectName)</NMakeBuildCommandLine>\n"
		"  <NMakeReBuildCommandLine>$(ProductDir)MeteorBuild.exe -rebuild -c $(Configuration) -m $(ProjectName)</NMakeReBuildCommandLine>\n"
		"  <NMakeCleanCommandLine>$(ProductDir)MeteorBuild.exe -clean -c $(Configuration) -m $(ProjectName)</NMakeCleanCommandLine>\n"
		"  <NMakeOutput>%s.dll</NMakeOutput>\n"
		"  <NMakePreprocessorDefinitions>MR_%s_EXPORT;$(NMakePreprocessorDefinitions)</NMakePreprocessorDefinitions>\n"
		"  <NMakeIncludeSearchPath>%s</NMakeIncludeSearchPath>\n"
		"  <ExecutablePath>$(ProductDir);$(ExecutablePath)</ExecutablePath>\n"
		" </PropertyGroup>\n"
		" <ItemGroup>\n";

	inline constexpr const char BottomPart[] =
		" </ItemGroup>\n"
		" <ItemGroup>\n"
		"  <BuildMacro Include=\"ProductDir\">\n"
		"   <Value>$(ProductDir)</Value>\n"
		"  </BuildMacro>\n"
		"  <BuildMacro Include=\"ModuleDir\">\n"
		"   <Value>$(ModuleDir)</Value>\n"
		"  </BuildMacro>\n"
		" </ItemGroup>\n"
		" <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.targets\" />\n"
		" <ImportGroup Label=\"ExtensionTargets\">\n"
		" </ImportGroup>\n"
		"</Project>";
}

namespace Solution
{
	inline constexpr const char Header[] =
		"\n"
		"Microsoft Visual Studio Solution File, Format Version 12.00\n"
		"# Generated by MeteorBuild (R)\n"
		"# Visual Studio Version 18\n"
		"VisualStudioVersion = 18.6.11822.322 stable\n"
		"MinimumVisualStudioVersion = 10.0.40219.1";
}